# create a deployment file for Eureka in stage environment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: i27-eureka-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: i27-eureka-prod
  template:
    metadata:
      labels:
        app: i27-eureka-prod
    spec:
      containers:
      - name: i27-eureka-prod
        image: DIT #Docker image tag which will be replaced later by sharedlib
---
apiVersion: v1
kind: Service
metadata:
  name: i27-eureka-prod-svc
spec:
  selector:
    app: i27-eureka-prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8761
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: i27-eureka-prod-ingress
spec:
  rules:
  - host: eureka-prod.vishnuapple.in
    http:
      paths: 
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: i27-eureka-prod-svc
            port:
              number: 80