# create a deployment file for Eureka in tst environment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: i27-eureka-tst
spec:
  replicas: 1
  selector:
    matchLabels:
      app: i27-eureka-tst
  template:
    metadata:
      labels:
        app: i27-eureka-tst
    spec:
      imagePullSecrets:
      - name: jfrog-docker-secret # this is we are calling kubernetes secrets which we gave the command
      containers:
      - name: i27-eureka-tst
        image: DIT #Docker image tag which will be replaced later by sharedlib
---
apiVersion: v1
kind: Service
metadata:
  name: i27-eureka-tst-svc
spec:
  selector:
    app: i27-eureka-tst
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8761
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: i27-eureka-tst-ingress
spec:
  rules:
  - host: eureka-tst.vishnuapple.in
    http:
      paths: 
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: i27-eureka-tst-svc
            port:
              number: 80     